name: Docker Build and Push

on:
  repository_dispatch:
    types: [trigger-docker-build]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main  # 確保使用最新的主分支代碼

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/mayohr-auto-punch:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/mayohr-auto-punch:${{ github.event.client_payload.version }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/mayohr-auto-punch:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/mayohr-auto-punch:buildcache,mode=max